### ISSUE TITLE
KeyError: 'state_dict' from discord-stable-diffusion\src\stablediffusion\ldm\generate.py

### ISSUE THREAD

**Issue by YamakoVR** [harubaru/discord-stable-diffusion#15]
I have been following the following steps, using Windows 11 : 
- Installed CUBA Toolkit 
- Cloned the repository through Github Desktop
- Ran `setup.bat` and completed the venv installation
- Modified the `run.bat` file to fill the model.ckpt location and the Discord bot token
- Tested `/dream` command with the following query : "a girl drinking soda"

Seeing the same error `KeyError: 'state_dict'` after multiple queries attempts, I uninstalled and redone all the above steps. But it's no use: there is still that same error.

Here's what happens from the cmd, and the displayed error on Discord :

Request -- YamakoKiasote#2844 -- Prompt: a girl drinking soda
[2022-11-30 15:20:59] INFO: Global seed set to 1105693868
[2022-11-30 15:20:59] INFO: Global seed set to 1070861717
>> Loading model from C:\Users\yamak\stable-diffusion\models\Stable-diffusion\model.ckpt
Traceback (most recent call last):
  File "C:\Users\yamak\discord-stable-diffusion\src\bot\stablecog.py", line 161, in dream
    samples, seed = self.text2image_model.dream(queue_object.prompt, queue_object.steps, False, False, 0.0,
  File "C:\Users\yamak\discord-stable-diffusion\src\stablediffusion\text2image_compvis.py", line 64, in dream
    results = self.generator.txt2img(prompt=prompt, iterations = 1, steps=ddim_steps, seed=seed, cfg_scale=cfg_scale, ddim_eta=ddim_eta, width=width, height=height, sampler_name=sampler_name, outdir='storage/outputs')
  File "C:\Users\yamak\discord-stable-diffusion\src\stablediffusion\ldm\generate.py", line 175, in txt2img
    return self.prompt2png(prompt, outdir, **kwargs)
  File "C:\Users\yamak\discord-stable-diffusion\src\stablediffusion\ldm\generate.py", line 162, in prompt2png
    results = self.prompt2image(prompt, **kwargs)
  File "C:\Users\yamak\discord-stable-diffusion\src\stablediffusion\ldm\generate.py", line 263, in prompt2image
    self.load_model()
  File "C:\Users\yamak\discord-stable-diffusion\src\stablediffusion\ldm\generate.py", line 426, in load_model
    model = self._load_model_from_config(config, self.weights)
  File "C:\Users\yamak\discord-stable-diffusion\src\stablediffusion\ldm\generate.py", line 538, in _load_model_from_config
    sd = pl_sd['state_dict']
KeyError: 'state_dict'

![image](https://user-images.githubusercontent.com/78237334/204821158-80317aa0-338d-4eca-b28b-fbcc97ad656a.png)

**Comment by YamakoVR** [comment]
**One solution found**

You can update to the latest version of WD model
